ALTER TABLE configuracoes_site
  MODIFY logo_url LONGTEXT,
  MODIFY favicon_url LONGTEXT,
  MODIFY descricao_site LONGTEXT,
  MODIFY rodape_texto LONGTEXT,
  MODIFY meta_descricao LONGTEXT,
  ADD COLUMN logo_icon VARCHAR(120) DEFAULT 'ri-government-line',
  ADD COLUMN slogan_logo VARCHAR(255) DEFAULT 'Cuidando do Futuro de Quem Cuida da Cidade',
  ADD COLUMN slogan_image_url LONGTEXT,
  ADD COLUMN slogan_image_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN slogan_image_local VARCHAR(120) DEFAULT 'navbar,footer',
  ADD COLUMN pro_gestao_selo_url LONGTEXT,
  ADD COLUMN pro_gestao_link VARCHAR(255) DEFAULT '/pro-gestao',
  ADD COLUMN pro_gestao_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN pro_gestao_locais VARCHAR(255) DEFAULT 'navbar,footer,home,conteudo',
  ADD COLUMN contracheque_url VARCHAR(255),
  ADD COLUMN map_embed_url LONGTEXT,
  ADD COLUMN horario_sab VARCHAR(255),
  ADD COLUMN horario_dom VARCHAR(255),
  ADD COLUMN topbar_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN topbar_email_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN topbar_telefone_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN topbar_redes_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN topbar_mapa_site_visivel INT NOT NULL DEFAULT 1,
  ADD COLUMN layout_zoom INT NOT NULL DEFAULT 100,
  ADD COLUMN border_radius VARCHAR(40) DEFAULT 'lg';
